#!/usr/bin/env python3
"""Explode brian-oconner-roman-pearce.gif into the JPEG frames the app plays.

The badge's gfx.image() only speaks PNG and baseline JPEG (see
src/lua_sdk/lib_gfx.cpp) - there is no GIF decoder on the device, and the
source GIF is 2.4 MB against a 256 KB per-file limit anyway. So the GIF stays
in the app directory as the source asset, and this script is what turns it
into something the firmware can actually draw: one baseline JPEG per frame,
downscaled to the panel's 320x240 so main.lua never has to scale on the fly,
plus a durations.lua next to them with the per-frame delay pulled straight
out of the GIF (so a re-timed source regenerates a re-timed app).

Requires Pillow. Run from anywhere:

    python3 apps/forget/tools/make-frames.py
"""

import os

from PIL import Image, ImageSequence

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)
SOURCE = os.path.join(OUT, "brian-oconner-roman-pearce.gif")

# Matches config.h's LCD_WIDTH/LCD_HEIGHT. The source is 640x480 - exactly 2x
# this - so frames scale down with no letterboxing.
PANEL_W, PANEL_H = 320, 240

JPEG_QUALITY = 82


def main():
    im = Image.open(SOURCE)
    durations = []

    frame_no = 0
    for frame in ImageSequence.Iterator(im):
        frame_no += 1
        # Pillow composites disposal-method frames onto a running canvas as it
        # seeks, so converting straight to RGB here is enough - no manual
        # frame-diffing needed.
        rgb = frame.convert("RGB").resize((PANEL_W, PANEL_H), Image.LANCZOS)
        name = "frame-%02d.jpg" % frame_no
        rgb.save(os.path.join(OUT, name), "JPEG", quality=JPEG_QUALITY, optimize=True)
        durations.append(frame.info.get("duration", 100))

    # Milliseconds in the GIF, seconds in Lua - on_update(dt) already works in
    # seconds, so converting once here saves every frame doing it at runtime.
    lines = ["-- Generated by tools/make-frames.py - do not edit by hand.", ""]
    lines.append("return {")
    for ms in durations:
        lines.append("  %s," % (ms / 1000.0))
    lines.append("}")
    with open(os.path.join(OUT, "durations.lua"), "w") as f:
        f.write("\n".join(lines) + "\n")

    print("wrote %d frame(s) + durations.lua" % frame_no)


if __name__ == "__main__":
    main()
